# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.10
_src_path: https://github.com/jupyterlab/extension-template
author_email: me@test.com
author_name: My Name
has_binder: false
has_settings: false
kind: frontend
labextension_name: shout_button_message
project_short_description: An extension that adds a button and message to the right
    toolbar, with optional status bar widget in JupyterLab.
python_name: shout_button_message
repository: ''
test: false

